from fpdf import FPDF
import pandas as pd
import os

def generate_pdf_report(df, output_path, title, author):
    try:
        pdf = FPDF()
        pdf.add_page()
        
        # Title
        pdf.set_font("Arial", 'B', 20)
        pdf.cell(0, 20, title, ln=True, align='C')
        
        # Subtitle
        pdf.set_font("Arial", 'I', 12)
        pdf.cell(0, 10, f"Generated by: {author}", ln=True, align='C')
        pdf.cell(0, 10, f"Date: {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M')}", ln=True, align='C')
        pdf.ln(10)
        
        # Executive Summary
        pdf.set_font("Arial", 'B', 16)
        pdf.cell(0, 10, "1. Executive Summary", ln=True)
        pdf.set_font("Arial", '', 12)
        
        total_tx = len(df)
        fraud_df = df[df['Is Fraud'] == 1]
        total_fraud = len(fraud_df)
        fraud_pct = (total_fraud / total_tx) * 100
        total_amt = df['Transaction Amount'].sum()
        fraud_amt = fraud_df['Transaction Amount'].sum()
        
        summary = f"This report provides an analysis of {total_tx:,} financial transactions. " \
                  f"Our AI system identified {total_fraud:,} fraudulent transactions, representing {fraud_pct:.2f}% of the total volume. " \
                  f"The total financial exposure to fraud is estimated at INR {fraud_amt:,.2f} out of a total transaction volume of INR {total_amt:,.2f}."
        
        pdf.multi_cell(0, 10, summary)
        pdf.ln(5)
        
        # Dataset Overview
        pdf.set_font("Arial", 'B', 16)
        pdf.cell(0, 10, "2. Dataset Overview", ln=True)
        pdf.set_font("Arial", '', 12)
        
        overview = f"- Total Records: {total_tx}\n" \
                   f"- Date Range: {df['Transaction Date'].min()} to {df['Transaction Date'].max()}\n" \
                   f"- Features Analyzed: Amount, Type, Method, Location, Device, Time, etc.\n" \
                   f"- Target Variable: Is Fraud (Binary)"
        pdf.multi_cell(0, 10, overview)
        pdf.ln(5)
        
        # Fraud Statistics
        pdf.set_font("Arial", 'B', 16)
        pdf.cell(0, 10, "3. Key Fraud Statistics", ln=True)
        pdf.set_font("Arial", '', 12)
        
        stats = f"- Fraudulent Transactions: {total_fraud}\n" \
                f"- Legitimate Transactions: {total_tx - total_fraud}\n" \
                f"- Fraud Rate: {fraud_pct:.2f}%\n" \
                f"- Average Fraudulent Amount: INR {fraud_df['Transaction Amount'].mean():,.2f}\n" \
                f"- Highest Fraudulent Amount: INR {fraud_df['Transaction Amount'].max():,.2f}"
        pdf.multi_cell(0, 10, stats)
        pdf.ln(5)
        
        # Top Suspicious Transactions
        pdf.set_font("Arial", 'B', 16)
        pdf.cell(0, 10, "4. Top Suspicious Transactions", ln=True)
        pdf.set_font("Arial", 'B', 10)
        
        # Table Header
        pdf.cell(40, 10, "Transaction ID", 1)
        pdf.cell(40, 10, "Customer ID", 1)
        pdf.cell(40, 10, "Amount (INR)", 1)
        pdf.cell(60, 10, "Type", 1)
        pdf.ln()
        
        pdf.set_font("Arial", '', 10)
        top_fraud = fraud_df.sort_values(by='Transaction Amount', ascending=False).head(10)
        for _, row in top_fraud.iterrows():
            pdf.cell(40, 10, str(row['Transaction ID']), 1)
            pdf.cell(40, 10, str(row['Customer ID']), 1)
            pdf.cell(40, 10, f"{row['Transaction Amount']:,.2f}", 1)
            pdf.cell(60, 10, str(row['Transaction Type']), 1)
            pdf.ln()
            
        pdf.ln(10)
        
        # Recommendations
        pdf.set_font("Arial", 'B', 16)
        pdf.cell(0, 10, "5. Preventive Recommendations", ln=True)
        pdf.set_font("Arial", '', 12)
        
        recs = "1. Implement Multi-Factor Authentication (MFA) for all high-value transactions (> INR 50,000).\n" \
               "2. Flag and hold transactions occurring between 12 AM and 5 AM for manual review.\n" \
               "3. Monitor accounts with sudden increases in transaction frequency or international activity.\n" \
               "4. Educate customers about phishing and secure digital payment practices.\n" \
               "5. Regularly retrain ML models with new fraud patterns to maintain high detection accuracy."
        pdf.multi_cell(0, 10, recs)
        
        # Conclusion
        pdf.ln(5)
        pdf.set_font("Arial", 'B', 16)
        pdf.cell(0, 10, "6. Conclusion", ln=True)
        pdf.set_font("Arial", '', 12)
        pdf.multi_cell(0, 10, "The AI-powered fraud detection system effectively identifies suspicious activities with high recall. " \
                            "Continuous monitoring and human-in-the-loop verification are recommended for optimal financial security.")
        
        pdf.output(output_path)
        return True
    except Exception as e:
        print(f"Error generating PDF: {e}")
        return False
